/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import code.Card;
import code.OrderType;
import code.Payment;
import code.Order;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author tiara
 */
public class Confirm extends javax.swing.JFrame {

    /**
     * Creates new form Confirm
     */
    public Confirm() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dim.width-getWidth())/2;
        int y = (dim.height-getHeight())/2;
        setLocation(x, y);
        choice.setEnabled(false);
        choice.setVisible(false);
        bank.setEnabled(false);
        bank.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        date = new com.toedter.calendar.JDateChooser();
        self_pickup = new javax.swing.JRadioButton();
        delivery = new javax.swing.JRadioButton();
        credit = new javax.swing.JRadioButton();
        m_banking = new javax.swing.JRadioButton();
        choice = new RoundedPanel(20, new Color(229,229,229));
        bca = new javax.swing.JRadioButton();
        bni = new javax.swing.JRadioButton();
        mandiri = new javax.swing.JRadioButton();
        debit = new javax.swing.JRadioButton();
        bank1 = new javax.swing.JLabel();
        bank = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        confirm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        base = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 140, 142));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 229, 141));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        kGradientPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 160, -1));

        self_pickup.setBackground(new java.awt.Color(229, 229, 229));
        self_pickup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        self_pickup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                self_pickupActionPerformed(evt);
            }
        });
        kGradientPanel1.add(self_pickup, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 20, 20));

        delivery.setBackground(new java.awt.Color(229, 229, 229));
        delivery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliveryMouseClicked(evt);
            }
        });
        delivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryActionPerformed(evt);
            }
        });
        kGradientPanel1.add(delivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 20, 20));

        credit.setBackground(new java.awt.Color(229, 229, 229));
        credit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditActionPerformed(evt);
            }
        });
        kGradientPanel1.add(credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 20, 20));

        m_banking.setBackground(new java.awt.Color(229, 229, 229));
        m_banking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        m_banking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_bankingActionPerformed(evt);
            }
        });
        kGradientPanel1.add(m_banking, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 20, 20));

        choice.setBackground(new java.awt.Color(255, 255, 255));
        choice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bca.setBackground(new java.awt.Color(229, 229, 229));
        bca.setFont(new java.awt.Font("Montserrat Medium", 0, 10)); // NOI18N
        bca.setText("Bank BCA");
        bca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaActionPerformed(evt);
            }
        });
        choice.add(bca, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 7, 108, -1));

        bni.setBackground(new java.awt.Color(229, 229, 229));
        bni.setFont(new java.awt.Font("Montserrat Medium", 0, 10)); // NOI18N
        bni.setText("Bank BNI");
        bni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bniActionPerformed(evt);
            }
        });
        choice.add(bni, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, -1, -1));

        mandiri.setBackground(new java.awt.Color(229, 229, 229));
        mandiri.setFont(new java.awt.Font("Montserrat Medium", 0, 10)); // NOI18N
        mandiri.setText("Bank Mandiri");
        mandiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mandiriActionPerformed(evt);
            }
        });
        choice.add(mandiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 49, -1, -1));

        kGradientPanel1.add(choice, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 120, 90));

        debit.setBackground(new java.awt.Color(229, 229, 229));
        debit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        debit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitActionPerformed(evt);
            }
        });
        kGradientPanel1.add(debit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 20, 20));

        bank1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bank1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bank1MouseClicked(evt);
            }
        });
        kGradientPanel1.add(bank1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 20, 20));

        bank.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bankMouseClicked(evt);
            }
        });
        kGradientPanel1.add(bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 20, 20));

        address.setBackground(new java.awt.Color(229, 229, 229));
        address.setBorder(null);
        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressKeyTyped(evt);
            }
        });
        kGradientPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 290, -1));

        confirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmMouseClicked(evt);
            }
        });
        kGradientPanel1.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 394, 100, 20));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 70, 20));

        amount.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        kGradientPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 100, 30));

        jLabel8.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel8.setText("Cake     :");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 70, 20));

        jLabel3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel3.setText("Size       :");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 70, 20));

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel4.setText("Shape   :");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 70, 20));

        jLabel7.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel7.setText("Shipping cost :");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 90, 20));

        jLabel9.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel9.setText("Flavor   :");
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 70, 20));

        jLabel10.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel10.setText("Layer    :");
        kGradientPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 70, 20));

        cake.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        kGradientPanel1.add(cake, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 220, 20));

        size.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        kGradientPanel1.add(size, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 220, 20));

        shape.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        kGradientPanel1.add(shape, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 220, 20));

        flavor.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        kGradientPanel1.add(flavor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 220, 20));

        layer.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        kGradientPanel1.add(layer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 220, 20));

        note1.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        kGradientPanel1.add(note1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 220, 20));

        jLabel11.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel11.setText("Note     :");
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 70, 20));

        jLabel12.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel12.setText("SubTotal           :");
        kGradientPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 90, 20));

        subTotal.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        kGradientPanel1.add(subTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 140, 20));

        tax.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        kGradientPanel1.add(tax, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 140, 20));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jLabel5.setText("Rp");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        jLabel13.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel13.setText("Tax                      :");
        kGradientPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 90, 20));

        shipping.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        kGradientPanel1.add(shipping, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 140, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/konfirmasi.png"))); // NOI18N
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        base.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Rectangle 1.png"))); // NOI18N
        kGradientPanel1.add(base, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void self_pickupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_self_pickupActionPerformed
        if(self_pickup.isSelected()){
            delivery.setSelected(false);
            address.setEnabled(false);
        }
    }//GEN-LAST:event_self_pickupActionPerformed

    private void deliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryActionPerformed
        if(delivery.isSelected()){
            self_pickup.setSelected(false);
            address.setEnabled(true);
        }
    }//GEN-LAST:event_deliveryActionPerformed

    private void creditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditActionPerformed
        if(credit.isSelected()){
            debit.setSelected(false);
            m_banking.setSelected(false);
        }
    }//GEN-LAST:event_creditActionPerformed

    private void m_bankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_bankingActionPerformed
        if(m_banking.isSelected()){
            debit.setSelected(false);
            credit.setSelected(false);
        }
    }//GEN-LAST:event_m_bankingActionPerformed

    private void debitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitActionPerformed
        if(debit.isSelected()){
            credit.setSelected(false);
            m_banking.setSelected(false);
        }
    }//GEN-LAST:event_debitActionPerformed

    private void bcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaActionPerformed
        if(bca.isSelected()){
            bni.setSelected(false);
            mandiri.setSelected(false);
        }
    }//GEN-LAST:event_bcaActionPerformed

    private void bniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bniActionPerformed
        if(bni.isSelected()){
            bca.setSelected(false);
            mandiri.setSelected(false);
        }
    }//GEN-LAST:event_bniActionPerformed

    private void mandiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mandiriActionPerformed
        if(mandiri.isSelected()){
            bni.setSelected(false);
            bca.setSelected(false);
        }
    }//GEN-LAST:event_mandiriActionPerformed

    private void bank1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bank1MouseClicked
        choice.setEnabled(true);
        choice.setVisible(true);
        bank.setEnabled(true);
        bank.setVisible(true);
        bank1.setEnabled(false);
        bank1.setVisible(false);
    }//GEN-LAST:event_bank1MouseClicked

    private void bankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bankMouseClicked
        choice.setEnabled(false);
        choice.setVisible(false);
        bank.setEnabled(false);
        bank.setVisible(false);
        bank1.setEnabled(true);
        bank1.setVisible(true);
    }//GEN-LAST:event_bankMouseClicked

    private void confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseClicked
      
        SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
        String date_pickup = dateFormat.format(date.getDate());
        String type = "";
        if(delivery.isSelected()){
            type = "delivery";
        }if(self_pickup.isSelected()){
            type = "self pickup";
        }
        String add = address.getText();
        String method = "";
        if(debit.isSelected()){
            method = "debit";
        }if(credit.isSelected()){
            method = "credit";
        }if(m_banking.isSelected()){
            method = "mobile banking";
        }
        String uname = Customize.name1.getText();
        int t_amount = Integer.parseInt(amount.getText());
        
//==============================================================================
        Receipt.datePickUp.setText(date_pickup);
        Receipt.pickup.setText(type);
        Receipt.payment.setText(method);
        Receipt.cake.setText(this.cake.getText());
        Receipt.size.setText(this.size.getText());
        Receipt.shape.setText(this.shape.getText());
        Receipt.flavor.setText(this.flavor.getText());
        Receipt.layer.setText(this.layer.getText());
        Receipt.shipping.setText(this.shipping.getText());
        Receipt.total.setText(amount.getText());
//==============================================================================
        
        System.out.println(type);
        System.out.println(date_pickup);
        System.out.println(address.getText());
                int answer = JOptionPane.showConfirmDialog(null, "Are you sure?", "cakesie", JOptionPane.OK_OPTION);
                if (answer == JOptionPane.OK_OPTION){
                    OrderType ot = new OrderType(uname, type);
                    ot.selectType();

                    Card c = new Card();
                    c.makePayment(method, t_amount);
                    c.confirmPayment(uname, method, t_amount, add, date_pickup);
                    JOptionPane.showMessageDialog(null, "Thank you for your order!");
                    Receipt h = new Receipt();
                    h.setVisible(true);
                    this.dispose();
        }
        
        
    }//GEN-LAST:event_confirmMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Customize c = new Customize();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void addressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyTyped
        String add = address.getText();
        if(add.contains("Rungkut")){
            shipping.setText("10000");
        }if(add.contains("Gunung Anyar")){
            shipping.setText("15000");
        }if(add.contains("Wonocolo")){
            shipping.setText("20000");
        }if(add.contains("Buduran")){
            shipping.setText("25000");
        }
        
    }//GEN-LAST:event_addressKeyTyped

    private void deliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryMouseClicked

    }//GEN-LAST:event_deliveryMouseClicked

    private void addressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Order o = new Order();
            o.calTotal2();
        }
    }//GEN-LAST:event_addressKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(Exception e){
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Confirm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    public static final javax.swing.JLabel amount = new javax.swing.JLabel();
    private javax.swing.JLabel bank;
    private javax.swing.JLabel bank1;
    private javax.swing.JLabel base;
    private javax.swing.JRadioButton bca;
    private javax.swing.JRadioButton bni;
    public static final javax.swing.JLabel cake = new javax.swing.JLabel();
    private javax.swing.JPanel choice;
    private javax.swing.JLabel confirm;
    private javax.swing.JRadioButton credit;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JRadioButton debit;
    private javax.swing.JRadioButton delivery;
    public static final javax.swing.JLabel flavor = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    public static final javax.swing.JLabel layer = new javax.swing.JLabel();
    private javax.swing.JRadioButton m_banking;
    private javax.swing.JRadioButton mandiri;
    public static final javax.swing.JLabel note1 = new javax.swing.JLabel();
    private javax.swing.JRadioButton self_pickup;
    public static final javax.swing.JLabel shape = new javax.swing.JLabel();
    public static final javax.swing.JLabel shipping = new javax.swing.JLabel();
    public static final javax.swing.JLabel size = new javax.swing.JLabel();
    public static final javax.swing.JLabel subTotal = new javax.swing.JLabel();
    public static final javax.swing.JLabel tax = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
class RoundedPanel extends JPanel{
    private Color backgroundColor;
    private int cornerRadius = 15;
    
    public RoundedPanel(int radius, Color bgColor){
        super();
        cornerRadius = radius;
        backgroundColor = bgColor;
    }
    @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
}
}
