/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import code.Database;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import code.Customization;
import code.Order;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.UIManager;

/**
 *
 * @author tiara
 */
public class Customize extends javax.swing.JFrame {

    /**
     * Creates new form Temp
     */
    public Customize() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dim.width-getWidth())/2;
        int y = (dim.height-getHeight())/2;
        setLocation(x, y);
        c_price.setVisible(false);
        l_price.setVisible(false);
        w_price.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel15 = new javax.swing.JLabel();
        node = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        flavor = new javax.swing.JComboBox<>();
        note = new javax.swing.JTextField();
        home = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        custom = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        c1 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        c3 = new javax.swing.JRadioButton();
        c2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        layer = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        next = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        base = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 140, 142));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 229, 141));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cakesie.png"))); // NOI18N
        kGradientPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 80, 30));

        node.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        node.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/node.png"))); // NOI18N
        kGradientPanel1.add(node, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 20, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo (50 x 50 px).png"))); // NOI18N
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        flavor.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        flavor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Brownies", "Red Velvet", "Rainbow Cake", "Choco Cookies", "Tiramisu", "Cheese Cake" }));
        flavor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                flavorKeyPressed(evt);
            }
        });
        kGradientPanel1.add(flavor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 220, -1));

        note.setFont(new java.awt.Font("Montserrat Medium", 0, 10)); // NOI18N
        kGradientPanel1.add(note, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 220, 30));

        home.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("Home");
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        kGradientPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 70, 30));

        menu.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu.setText("Menu");
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });
        kGradientPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 70, 30));

        custom.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        custom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custom.setText("Customize");
        custom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel1.add(custom, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 80, 30));

        contact.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contact.setText("Contact");
        contact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactMouseClicked(evt);
            }
        });
        kGradientPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 70, 30));

        r1.setBackground(new java.awt.Color(255, 255, 255));
        r1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        r1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                r1KeyPressed(evt);
            }
        });
        kGradientPanel1.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 20, -1));

        r2.setBackground(new java.awt.Color(255, 255, 255));
        r2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        r2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                r2KeyPressed(evt);
            }
        });
        kGradientPanel1.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 20, -1));

        c1.setBackground(new java.awt.Color(255, 255, 255));
        c1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        c1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                c1KeyPressed(evt);
            }
        });
        kGradientPanel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 20, 20));

        r3.setBackground(new java.awt.Color(255, 255, 255));
        r3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        r3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                r3KeyPressed(evt);
            }
        });
        kGradientPanel1.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 20, -1));

        c3.setBackground(new java.awt.Color(255, 255, 255));
        c3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        c3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                c3KeyPressed(evt);
            }
        });
        kGradientPanel1.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 20, -1));

        c2.setBackground(new java.awt.Color(255, 255, 255));
        c2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        c2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                c2KeyPressed(evt);
            }
        });
        kGradientPanel1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 20, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/custom.png"))); // NOI18N
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 320, -1));

        layer.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        layer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Butter Cream", "Fondant", "Royal Icing" }));
        layer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                layerKeyPressed(evt);
            }
        });
        kGradientPanel1.add(layer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 220, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel2.setText("SubTotal    :");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 100, 20));

        jLabel3.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel3.setText("Layer");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 80, 20));

        jLabel4.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel4.setText("Flavor");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 80, 20));

        jLabel7.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel7.setText("Add Note");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 80, 20));

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/next.png"))); // NOI18N
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });
        kGradientPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel8.setText("Cake");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 80, 20));

        subTotal.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        subTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        subTotal.setBorder(null);
        kGradientPanel1.add(subTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 80, -1));

        cake1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        kGradientPanel1.add(cake1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 220, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        base.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Rectangle 1.png"))); // NOI18N
        kGradientPanel1.add(base, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        kGradientPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 90, 20));

        c_price.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        c_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_price.setText("0");
        c_price.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        c_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                c_priceKeyPressed(evt);
            }
        });
        kGradientPanel1.add(c_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 90, -1));

        l_price.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        l_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        l_price.setText("0");
        l_price.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        kGradientPanel1.add(l_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 90, -1));

        w_price.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        w_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        w_price.setText("0");
        w_price.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        w_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                w_priceKeyPressed(evt);
            }
        });
        kGradientPanel1.add(w_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 60, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        if(c1.isSelected()){
            c2.setSelected(false);
            c3.setSelected(false);
            r1.setSelected(false);
            r2.setSelected(false);
            r3.setSelected(false);
        
        String cake = cake1.getText();
        String width = "";
        String size ="13 cm";
        String shape = "Circle";
        if(c1.isSelected()){
            width = "13";
        }
        Order o = new Order();
        o.getWidthPrice(width);
        o.getCakePrice(cake);
        o.getCakePrice(cake);
            o.calSubTotal();
            Confirm.shape.setText(shape);
            Confirm.size.setText(size);
            Confirm.cake.setText(cake);
        
        }
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        if(c2.isSelected()){
            c1.setSelected(false);
            c3.setSelected(false);
            r1.setSelected(false);
            r2.setSelected(false);
            r3.setSelected(false);
        
        String cake = cake1.getText();
        String size ="18 cm";
        String shape = "Circle";
        String width = "";
        if(c2.isSelected()){
            width = "18";
        }
        Order o = new Order();
        o.getWidthPrice(width);
        o.getCakePrice(cake);
            o.calSubTotal();
            Confirm.shape.setText(shape);
            Confirm.size.setText(size);
            Confirm.cake.setText(cake);
        
        }
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        if(c3.isSelected()){
            c2.setSelected(false);
            c1.setSelected(false);
            r1.setSelected(false);
            r2.setSelected(false);
            r3.setSelected(false);
        String cake = cake1.getText();
        String size ="21 cm";
        String shape = "Circle";
        String width = "";
        if(c3.isSelected()){
            width = "21";
        }
        Order o = new Order();
        o.getWidthPrice(width);
        o.getCakePrice(cake);
            o.calSubTotal();
            Confirm.shape.setText(shape);
            Confirm.size.setText(size);
            Confirm.cake.setText(cake);
        
        }
    }//GEN-LAST:event_c3ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        if(r1.isSelected()){
            c2.setSelected(false);
            c3.setSelected(false);
            c1.setSelected(false);
            r2.setSelected(false);
            r3.setSelected(false);
        String cake = cake1.getText();
        String size ="13 cm";
        String shape = "Rectangle";
        String width = "";
        if(r1.isSelected()){
            width = "13";
        }
        Order o = new Order();
        o.getWidthPrice(width);
        o.getCakePrice(cake);
            o.calSubTotal();
            Confirm.shape.setText(shape);
            Confirm.size.setText(size);
            Confirm.cake.setText(cake);
        
        }
    }//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        if(r2.isSelected()){
            c2.setSelected(false);
            c3.setSelected(false);
            r1.setSelected(false);
            c1.setSelected(false);
            r3.setSelected(false);
            
        String cake = cake1.getText();
        String size ="18 cm";
        String shape = "Rectangle";
        String width = "";
        if(r2.isSelected()){
            width = "18";
        }
        Order o = new Order();
        o.getWidthPrice(width);
        o.getCakePrice(cake);
            o.calSubTotal();
            Confirm.shape.setText(shape);
            Confirm.size.setText(size);
            Confirm.cake.setText(cake);
        
        }
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        if(r3.isSelected()){
            c2.setSelected(false);
            c3.setSelected(false);
            r1.setSelected(false);
            r2.setSelected(false);
            c1.setSelected(false);
            
        String cake = cake1.getText();
        String size ="21 cm";
        String shape = "Rectangle";
        String width = "";
        if(r3.isSelected()){
            width = "21";
        }
        Order o = new Order();
        o.getWidthPrice(width);
        o.getCakePrice(cake);
            o.calSubTotal();
            Confirm.shape.setText(shape);
            Confirm.size.setText(size);
            Confirm.cake.setText(cake);
        
        }
    }//GEN-LAST:event_r3ActionPerformed

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        String uname = Customize.name1.getText();
        String cake = cake1.getText();
        
        String width = "";
        String shape = "";
        if(c1.isSelected()){
            width = "W01";
            shape = "S01";
        } if(c2.isSelected()){
            width = "W02";
            shape = "S01";
        } if(c3.isSelected()){
            width = "W03";
            shape = "S01";
        } if(r1.isSelected()){
            width = "W01";
            shape = "S02";
        } if(r2.isSelected()){
            width = "W02";
            shape = "S02";
        } if(r3.isSelected()){
            width = "W03";
            shape = "S02";
        }
        
        String flavor = this.flavor.getSelectedItem().toString();
        String layer = this.layer.getSelectedItem().toString();
        String note = this.note.getText();
        
        System.out.println(width);
        Customization c = new Customization(uname);
        c.makeOrder();
        c.customCake(cake, width, shape, flavor, layer, note);
        
        Confirm co = new Confirm();
        co.setVisible(true);
        Order o = new Order();
        o.calTotal();
        String f = this.flavor.getSelectedItem().toString();
        String n = this.note.getText();
        Confirm.flavor.setText(f);
        Confirm.note1.setText(n);
        this.dispose();
        
    }//GEN-LAST:event_nextMouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        Menu1 m = new Menu1();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        Home1 h = new Home1();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void contactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseClicked
        Contact c = new Contact();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_contactMouseClicked

    private void c1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c1KeyPressed
        
    }//GEN-LAST:event_c1KeyPressed

    private void c2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c2KeyPressed
        
    }//GEN-LAST:event_c2KeyPressed

    private void c3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c3KeyPressed
        
    }//GEN-LAST:event_c3KeyPressed

    private void r1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_r1KeyPressed
        
    }//GEN-LAST:event_r1KeyPressed

    private void r2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_r2KeyPressed
        
    }//GEN-LAST:event_r2KeyPressed

    private void r3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_r3KeyPressed
        
    }//GEN-LAST:event_r3KeyPressed

    private void flavorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_flavorKeyPressed
        
    }//GEN-LAST:event_flavorKeyPressed

    private void layerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_layerKeyPressed
        String cake = cake1.getText();
        String name = layer.getSelectedItem().toString();
        Order o = new Order();
        o.getLayerPrice(name);
        o.getCakePrice(cake);
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            o.calSubTotal();
            Confirm.layer.setText(name);
            Confirm.cake.setText(cake);
        }
    }//GEN-LAST:event_layerKeyPressed

    private void w_priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_w_priceKeyPressed
        
    }//GEN-LAST:event_w_priceKeyPressed

    private void c_priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_priceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_priceKeyPressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        subTotal.setText("");
        c1.setSelected(false);
        c2.setSelected(false);
        c3.setSelected(false);
        r1.setSelected(false);
        r2.setSelected(false);
        r3.setSelected(false);
        layer.setSelectedItem("select");
        flavor.setSelectedItem("select");
        Menu1 m = new Menu1();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(Exception e){
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customize().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel base;
    private javax.swing.JRadioButton c1;
    private javax.swing.JRadioButton c2;
    private javax.swing.JRadioButton c3;
    public static final javax.swing.JTextField c_price = new javax.swing.JTextField();
    public static final javax.swing.JLabel cake1 = new javax.swing.JLabel();
    private javax.swing.JLabel contact;
    private javax.swing.JLabel custom;
    private javax.swing.JComboBox<String> flavor;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    public static final javax.swing.JTextField l_price = new javax.swing.JTextField();
    private javax.swing.JComboBox<String> layer;
    private javax.swing.JLabel menu;
    public static final javax.swing.JLabel name1 = new javax.swing.JLabel();
    private javax.swing.JLabel next;
    private javax.swing.JLabel node;
    private javax.swing.JTextField note;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    public static final javax.swing.JTextField subTotal = new javax.swing.JTextField();
    public static final javax.swing.JTextField w_price = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
