/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import code.Database;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author tiara
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dim.width-getWidth())/2;
        int y = (dim.height-getHeight())/2;
        setLocation(x, y);
        id.setVisible(false);
        pass.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jUname = new javax.swing.JLabel();
        jPass = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        LogIn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jUname.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jUname.setForeground(new java.awt.Color(204, 204, 204));
        jUname.setText("username");
        jUname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jUname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jUnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jUnameMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jUnameMousePressed(evt);
            }
        });
        jPanel1.add(jUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 200, 20));

        jPass.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jPass.setForeground(new java.awt.Color(204, 204, 204));
        jPass.setText("password");
        jPass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPassMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPassMousePressed(evt);
            }
        });
        jPanel1.add(jPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 200, 20));

        id.setBackground(new java.awt.Color(245, 245, 245));
        id.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        id.setBorder(null);
        id.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 220, 20));

        pass.setBackground(new java.awt.Color(245, 245, 245));
        pass.setBorder(null);
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passKeyTyped(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 220, 20));

        LogIn.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        LogIn.setText("Login");
        LogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInMouseClicked(evt);
            }
        });
        jPanel1.add(LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 80, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loginNew.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInMouseClicked
        PreparedStatement ps;
        ResultSet rs;
        
        String id = this.id.getText();
        String pass = String.valueOf(this.pass.getPassword());
        String sql = "SELECT * FROM `user` WHERE `id` = ? AND `password` = ?";
            try{
                ps = Database.getConnection().prepareStatement(sql);
                ps.setString(1, id);
                ps.setString(2, pass);
                
                rs = ps.executeQuery();
                if(rs.next()){
                    if("customer".equals(rs.getString("role"))){
                        Home1 h = new Home1();
                        h.setVisible(true);
                        this.dispose();
                    }else if("owner".equals(rs.getString("role"))){
                        Order o = new Order();
                        o.setVisible(true);
                        this.dispose();
                    }else if("employee".equals(rs.getString("role"))){
                        EmpPreOrder o = new EmpPreOrder();
                        o.setVisible(true);
                        this.dispose();
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null,"Invalid Username/Password","Login Error",2);
                    this.pass.setText("");
                    jPass.setVisible(true);
//                    this.dispose();
//                    Dashboard d = new Dashboard();
//                    d.setVisible(true);
                }
                
            }catch (SQLException ex) {
                ex.printStackTrace();
                
            }
    }//GEN-LAST:event_LogInMouseClicked

    private void jUnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUnameMousePressed
        id.setVisible(true);
        jUname.setVisible(false);
        id.grabFocus();
    }//GEN-LAST:event_jUnameMousePressed

    private void jPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPassMousePressed
        pass.setVisible(true);
        jPass.setVisible(false);
        pass.grabFocus();
    }//GEN-LAST:event_jPassMousePressed

    private void jUnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUnameMouseEntered
        
    }//GEN-LAST:event_jUnameMouseEntered

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
            jUname.setVisible(false);
            if(id.getText().isBlank()){
            jUname.setVisible(true);
        }
    }//GEN-LAST:event_idKeyTyped

    private void passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyTyped
        jPass.setVisible(false);
        if(pass.getText().isEmpty()){
            jPass.setVisible(true);
        }
    }//GEN-LAST:event_passKeyTyped

    private void jPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPassMouseEntered
        
    }//GEN-LAST:event_jPassMouseEntered

    private void jUnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUnameMouseExited

    }//GEN-LAST:event_jUnameMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(Exception e){
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogIn;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPass;
    private javax.swing.JLabel jUname;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables
}
