/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.UIManager;


/**
 *
 * @author tiara
 */
public class Home1 extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Home1() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dim.width-getWidth())/2;
        int y = (dim.height-getHeight())/2;
        setLocation(x, y);
        logout.setEnabled(false);
        logout.setVisible(false);
        u.setEnabled(false);
        u.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        customNow = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        viewMenu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        custom = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        node = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        u = new javax.swing.JLabel();
        u1 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        base = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 140, 142));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 229, 141));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel2.setText("<html>\nYou can customize your own cake with various style. \n<br>\nWe provide numerous cake decoration and flavour.");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel1.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 30)); // NOI18N
        jLabel1.setText("<html>\nA simple way to\n<br>\ndecorate your\n<br>\ndream cake");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        customNow.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        customNow.setText("Customize now");
        customNow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customNow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customNowMouseClicked(evt);
            }
        });
        kGradientPanel1.add(customNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 120, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Arrow - Right Circle.png"))); // NOI18N
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, 50));

        viewMenu.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        viewMenu.setForeground(new java.awt.Color(255, 255, 255));
        viewMenu.setText("View Menu");
        viewMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewMenuMouseExited(evt);
            }
        });
        kGradientPanel1.add(viewMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 110, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/customize.png"))); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cakesie.png"))); // NOI18N
        kGradientPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 80, 30));

        home.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("Home");
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 70, 30));

        menu.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu.setText("Menu");
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });
        kGradientPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 70, 30));

        custom.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        custom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custom.setText("Customize");
        custom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        custom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customMouseClicked(evt);
            }
        });
        kGradientPanel1.add(custom, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 80, 30));

        name1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        name1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 140, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Rectangle 2.png"))); // NOI18N
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        node.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/node.png"))); // NOI18N
        kGradientPanel1.add(node, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo (50 x 50 px).png"))); // NOI18N
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/big logo.png"))); // NOI18N
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        contact.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contact.setText("Contact");
        contact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactMouseClicked(evt);
            }
        });
        kGradientPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 70, 30));

        u.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        u.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        u.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uMouseClicked(evt);
            }
        });
        kGradientPanel1.add(u, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 40, 40));

        u1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        u1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        u1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u1MouseClicked(evt);
            }
        });
        kGradientPanel1.add(u1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 40, 40));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        kGradientPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, -1, -1));

        base.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Rectangle 1.png"))); // NOI18N
        kGradientPanel1.add(base, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        Menu1Copy m = new Menu1Copy();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuMouseClicked

    private void customMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customMouseClicked
        IDForm c = new IDForm();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_customMouseClicked

    private void contactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseClicked
        Contact c = new Contact();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_contactMouseClicked

    private void customNowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customNowMouseClicked
        IDForm l = new IDForm();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_customNowMouseClicked

    private void viewMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMenuMouseClicked
        Menu1Copy m = new Menu1Copy();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewMenuMouseClicked

    private void viewMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMenuMouseEntered
        viewMenu.setForeground(Color.black);
    }//GEN-LAST:event_viewMenuMouseEntered

    private void viewMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMenuMouseExited
        viewMenu.setForeground(Color.white);
    }//GEN-LAST:event_viewMenuMouseExited

    private void uMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uMouseClicked
        logout.setEnabled(false);
        logout.setVisible(false);
        u.setEnabled(false);
        u.setVisible(false);
        u1.setEnabled(true);
        u1.setVisible(true);
    }//GEN-LAST:event_uMouseClicked

    private void u1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u1MouseClicked
        logout.setEnabled(true);
        logout.setVisible(true);
        u.setEnabled(true);
        u.setVisible(true);
        u1.setEnabled(false);
        u1.setVisible(false);
    }//GEN-LAST:event_u1MouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Dashboard d = new Dashboard();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(Exception e){
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel base;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel custom;
    private javax.swing.JLabel customNow;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel menu;
    public static final javax.swing.JLabel name1 = new javax.swing.JLabel();
    private javax.swing.JLabel node;
    private javax.swing.JLabel u;
    private javax.swing.JLabel u1;
    private javax.swing.JLabel viewMenu;
    // End of variables declaration//GEN-END:variables

        
}
