/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import code.Database;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tiara
 */
public class Inventory extends javax.swing.JFrame {

    /**
     * Creates new form Inventory
     */
    PreparedStatement ps;
    ResultSet rs;
    public Inventory() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dim.width-getWidth())/2;
        int y = (dim.height-getHeight())/2;
        setLocation(x, y);
        logout.setEnabled(false);
        logout.setVisible(false);
        u.setEnabled(false);
        u.setVisible(false);
        tampilCake();
        tampilLayer();
        tampilSize();
    }
    
    public void tampilCake(){
        clearCake();
        String sql = "select cake_id, cake_name, cake_price from cake";
        try{
            ps = Database.getConnection().prepareStatement(sql);
            rs = ps.executeQuery();
            
            while(rs.next()){
                String id = rs.getString("cake_id");
                String name = rs.getString("cake_name");
                String price = rs.getString("cake_price");
                
                Object[] obj = {id, name, price};
                DefaultTableModel table1 = (DefaultTableModel)jTable1.getModel();
                table1.addRow(obj);
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }
    public void tampilLayer(){
        clearLayer();
        String sql = "select layer_id, l_name, l_price from layer";
        try{
            ps = Database.getConnection().prepareStatement(sql);
            rs = ps.executeQuery();
            
            while(rs.next()){
                String id = rs.getString("layer_id");
                String name = rs.getString("l_name");
                String price = rs.getString("l_price");
                
                Object[] obj = {id, name, price};
                DefaultTableModel table1 = (DefaultTableModel)jTable2.getModel();
                table1.addRow(obj);
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }
    public void tampilSize(){
        clearSize();
        String sql = "select w_id, w_num, w_price from width";
        try{
            ps = Database.getConnection().prepareStatement(sql);
            rs = ps.executeQuery();
            
            while(rs.next()){
                String id = rs.getString("w_id");
                String name = rs.getString("w_num");
                String price = rs.getString("w_price");
                
                Object[] obj = {id, name, price};
                DefaultTableModel table1 = (DefaultTableModel)jTable3.getModel();
                table1.addRow(obj);
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }
    public void clearCake(){
        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
        table.setRowCount(0);
    }
    public void clearLayer(){
        DefaultTableModel table = (DefaultTableModel)jTable2.getModel();
        table.setRowCount(0);
    }
    public void clearSize(){
        DefaultTableModel table = (DefaultTableModel)jTable3.getModel();
        table.setRowCount(0);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JLabel();
        custom = new javax.swing.JLabel();
        history = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        node = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cake_id = new javax.swing.JTextField();
        cake_name = new javax.swing.JTextField();
        cake_price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        layer_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        layer_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        layer_price = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        size_id = new javax.swing.JTextField();
        size = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        u = new javax.swing.JLabel();
        u1 = new javax.swing.JLabel();
        base = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu.setText("Order");
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 70, 30));

        custom.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        custom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custom.setText("Item");
        custom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(custom, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 100, 30));

        history.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        history.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        history.setText("Report");
        history.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyMouseClicked(evt);
            }
        });
        jPanel1.add(history, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 70, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo (50 x 50 px).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cakesie.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 80, 30));

        node.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        node.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/node.png"))); // NOI18N
        jPanel1.add(node, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 20, -1));

        jTabbedPane1.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cake ID", "Cake Name", "Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 730, 210));

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel2.setText("Cake ID         :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel3.setText("Cake Name :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel4.setText("Price              :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        cake_id.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jPanel2.add(cake_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 150, 20));

        cake_name.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jPanel2.add(cake_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 150, 20));

        cake_price.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jPanel2.add(cake_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update_logo.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        jTabbedPane1.addTab("Cake", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel7.setText("Layer ID         :");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        layer_id.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jPanel4.add(layer_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 150, 20));

        jLabel8.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel8.setText("Layer Name :");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        layer_name.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jPanel4.add(layer_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 150, 20));

        jLabel9.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel9.setText("Price              :");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        layer_price.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jPanel4.add(layer_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Layer ID", "Layer Name", "Price"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 730, 120));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update_logo.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        jTabbedPane1.addTab("Layer", jPanel4);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel11.setText("Size ID          :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel12.setText("Size                :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel13.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel13.setText("Price              :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        size_id.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jPanel3.add(size_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 150, 20));

        size.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jPanel3.add(size, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 150, 20));

        price.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jPanel3.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Size ID", "Size", "Price"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 730, 120));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update_logo.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        jTabbedPane1.addTab("Size", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 760, 350));

        u.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        u.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        u.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uMouseClicked(evt);
            }
        });
        jPanel1.add(u, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 40, 40));

        u1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        u1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        u1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u1MouseClicked(evt);
            }
        });
        jPanel1.add(u1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 40, 40));

        base.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Rectangle 1.png"))); // NOI18N
        jPanel1.add(base, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        String id = cake_id.getText();
        String name = cake_name.getText();
        String price = cake_price.getText();
        
        String sql = "update cake set cake_price = ? where cake_id = ?";
        try{
            ps = Database.getConnection().prepareStatement(sql);
            ps.setString(1, price);
            ps.setString(2, id);

            ps.execute();
            
            JOptionPane.showMessageDialog(null, "Success Updating");
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        tampilCake();
        cake_id.setText("");
        cake_name.setText("");
        cake_price.setText("");
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        String id = jTable1.getModel().getValueAt(row, 0).toString();
        String name = jTable1.getModel().getValueAt(row, 1).toString();
        String price = jTable1.getModel().getValueAt(row, 2).toString();
        
        cake_id.setText(id);
        cake_name.setText(name);
        cake_price.setText(price);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int row = jTable2.getSelectedRow();
        String id = jTable2.getModel().getValueAt(row, 0).toString();
        String name = jTable2.getModel().getValueAt(row, 1).toString();
        String price = jTable2.getModel().getValueAt(row, 2).toString();
        
        layer_id.setText(id);
        layer_name.setText(name);
        layer_price.setText(price);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        String id = layer_id.getText();
        String name = layer_name.getText();
        String price = layer_price.getText();
        
        String sql = "update layer set l_price = ? where layer_id = ?";
        try{
            ps = Database.getConnection().prepareStatement(sql);
            ps.setString(1, price);
            ps.setString(2, id);

            ps.execute();
            
            JOptionPane.showMessageDialog(null, "Success Updating");
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        tampilLayer();
        layer_id.setText("");
        layer_name.setText("");
        layer_price.setText("");
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        int row = jTable3.getSelectedRow();
        String id = jTable3.getModel().getValueAt(row, 0).toString();
        String name = jTable3.getModel().getValueAt(row, 1).toString();
        String price = jTable3.getModel().getValueAt(row, 2).toString();
        
        size_id.setText(id);
        size.setText(name);
        this.price.setText(price);
    }//GEN-LAST:event_jTable3MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        String id = size_id.getText();
        String name = size.getText();
        String price = this.price.getText();
        
        String sql = "update width set w_price = ? where w_id = ?";
        try{
            ps = Database.getConnection().prepareStatement(sql);
            ps.setString(1, price);
            ps.setString(2, id);

            ps.execute();
            
            JOptionPane.showMessageDialog(null, "Success Updating");
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        tampilSize();
        size_id.setText("");
        size.setText("");
        this.price.setText("");
    }//GEN-LAST:event_jLabel14MouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        Order o = new Order();
        o.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuMouseClicked

    private void historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyMouseClicked
        Report r = new Report();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_historyMouseClicked

    private void uMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uMouseClicked
        logout.setEnabled(false);
        logout.setVisible(false);
        u.setEnabled(false);
        u.setVisible(false);
        u1.setEnabled(true);
        u1.setVisible(true);
    }//GEN-LAST:event_uMouseClicked

    private void u1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u1MouseClicked
        logout.setEnabled(true);
        logout.setVisible(true);
        u.setEnabled(true);
        u.setVisible(true);
        u1.setEnabled(false);
        u1.setVisible(false);
    }//GEN-LAST:event_u1MouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Dashboard d = new Dashboard();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(Exception e){
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel base;
    private javax.swing.JTextField cake_id;
    private javax.swing.JTextField cake_name;
    private javax.swing.JTextField cake_price;
    private javax.swing.JLabel custom;
    private javax.swing.JLabel history;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField layer_id;
    private javax.swing.JTextField layer_name;
    private javax.swing.JTextField layer_price;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel node;
    private javax.swing.JTextField price;
    private javax.swing.JTextField size;
    private javax.swing.JTextField size_id;
    private javax.swing.JLabel u;
    private javax.swing.JLabel u1;
    // End of variables declaration//GEN-END:variables
}
